### PR TITLE
Development

### PR DESCRIPTION
**Pull request by jchung05**
Today's meeting:

@SJuery removed unnecessary garbage files and created multiple functions

@ttran created multiple functions and submitted a .gitignore and author file

@jchung05 added in boilerplate main.c

Notes:

Consider opening up a scanf input for users when they use specific functions such as email or timer so that they can manually type in a value for field.

Hot word recognition to tie functions and boilerplate Sphinx program together.

### CODE REVIEW

**Review by regien — APPROVED** [review]
Review new pull request with team, and discuss about the content

**Review by sjuery — APPROVED** [review]
Sounds good, lets merge

**Comment by ttran42** [comment]
Gj

**Review by ttran42 — APPROVED** [review]
Higgh

**Pull request merged**
